apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: keycloak
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secret-keycloak
            namespace: keycloak
