apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appmod-ingress-master
  annotations:
    nginx.org/mergeable-ingress-type: "master"
spec:
  ingressClassName: nginx
  rules:
  - host: '*.amazonaws.com'
configs: 
  params:
    - server.insecure: true