apiVersion: v1
kind: Pod
metadata:
  name: rust-svc-load-test
  namespace: rust-msvc
  labels:
    workload: rust-svc-test
spec:
  containers:
    - name: artillery-container
      image: 779846826726.dkr.ecr.us-west-2.amazonaws.com/test/rust-svc # TODO: Use the integration image here
