apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: rust-images-distro
spec:
  forProvider:
    distributionConfig:
      comment: Rust application images distribution
      defaultCacheBehavior:
        forwardedValues:
          cookies:
            forward: none
          queryString: false
        minTTL: 0
        targetOriginID: s3Origin
        viewerProtocolPolicy: allow-all
      enabled: true
      origins:
        items:
          - domainName: crossplane-example-bucket.s3.amazonaws.com
            id: s3Origin
            s3OriginConfig:
              originAccessIdentity: ""
    region: us-east-1
  providerConfigRef:
    name: example
