apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: rust-app-service-role
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::771830474512:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/14F4B4F2E3C5B598E413B8CF4E206422"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-2.amazonaws.com/id/14F4B4F2E3C5B598E413B8CF4E206422:aud": "sts.amazonaws.com",
                    "oidc.eks.us-east-2.amazonaws.com/id/14F4B4F2E3C5B598E413B8CF4E206422:sub": "system:serviceaccount:external-secrets:external-secrets-sa"
                }
            }
        }
      ]
    }
  providerConfigRef:
    name: example
