apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  labels:
    addToInstanceProfile: "true"
  name: crossplane-iam-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
                "Service": "pods.eks.amazonaws.com"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:TagSession"
            ]
          }
        ]
      }
  providerConfigRef:
    name: upbound-aws-config
---
# IAM Policy
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicy
metadata:
  name: crossplane-iam-policy
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:PutObject"
            ],
            "Resource": [
              "arn:aws:s3:::eks-accelerator-5e5a6f7a-823c-0aa4-117f-5451b84277c4/*",
              "arn:aws:s3:::eks-accelerator-5e5a6f7a-823c-0aa4-117f-5451b84277c4"
            ]
          },
          {
            "Effect": "Allow",
            "Action": [
              "dynamodb:GetItem",
              "dynamodb:PutItem",
              "dynamodb:DeleteItem",
              "dynamodb:DescribeTable"
            ],
            "Resource": "arn:aws:dynamodb:us-west-2:6546546
            "Resource": "arn:aws:dynamodb:us-west-2:654654614242:table/eks-accelerator-tf-lock"
          }
        ]
      }
    roleRef:
      name: crossplane-iam-role
  providerConfigRef:
    name: upbound-aws-config
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/podidentityassociation
  labels:
    testing.upbound.io/example-name: crossplane-pia
  name: crossplane-pia
spec:
  forProvider:
    clusterName: modern-engineering
    namespace: pod-id
    region: us-west-2
    roleArnRef:
      name: crossplane-iam-role
    serviceAccount: team-test
  providerConfigRef:
    name: upbound-aws-config

