apiVersion: batch/v1
kind: Job
metadata:
  name: rust-app-setup
  namespace: rust-msvc  # TODO: Change this before going to workshop
spec:
  template:
    metadata:
      labels:
        app: rust-app-setup
    spec:
      serviceAccountName: rust-setup
      containers:
        - name: rust-setup
          image: 771830474512.dkr.ecr.us-west-2.amazonaws.com/test/rust-svc