apiVersion: v1
kind: Service
metadata:
  name: rust-app-svc  # rust-app-svc.argo-rollouts.svc.cluster.local
  namespace: rust-msvc  # TODO: Change this before going to workshop
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: rust-app
  ports:
    - port: 80
      targetPort: 8888
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rust-app-ingress
  namespace: rust-msvc
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rust-app-svc
                port:
                  number: 80
