apiVersion: batch/v1
kind: Job
metadata:
  name: rust-app-setup
  namespace: argo-rollouts  # TODO: Change this before going to workshop
spec:
  template:
    metadata:
      labels:
        app: rust-app-setup
    spec:
      serviceAccountName: rust-setup
      containers:
        - name: rust-setup
          image: 913524909446.dkr.ecr.us-west-2.amazonaws.com/setup/rust-service:latest