apiVersion: batch/v1
kind: Job
metadata:
  name: rust-app-setup
  namespace: rust-msvc
spec:
  template:
    metadata:
      labels:
        app: rust-app-setup
    spec:
      serviceAccountName: rust-setup
      containers:
        - name: rust-setup
          image: 389706897409.dkr.ecr.us-west-2.amazonaws.com/test/rust-svc