apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1beta1/table
  name: rust-microservice-table
spec:
  forProvider:
    attribute:
      - name: partition-key
        type: S
      - name: sort-key
        type: S
    hashKey: partition-key
    rangeKey: sort-key
    billingMode: PROVISIONED
    readCapacity: 20
    region: us-west-2
    tags:
      Environment: dev
    writeCapacity: 20