apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: devlake-rds-mysql
  namespace: devlake
spec:
  components:
    - name: devlake-mysql-db
      type: rds-cluster-mysql
      properties:
        region: us-west-2
        subnetIds:
          - $(SUBNET_ID_1)
          - $(SUBNET_ID_2)
          - $(SUBNET_ID_3)
        vpcId: $(VPC_ID)
        vpcCidr: 10.0.0.0/16
      traits:
        - type: component-iam-policy
          properties:
            service: rds-db
            policy: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Action": [
                      "rds-db:connect"
                    ],
                    "Resource": "*"
                  }
                ]
              }


    - name: devlake-mysql-access
      type: dp-service-account
      properties:
        clusterName: modern-engineering
        clusterRegion: us-west-2
        componentNamesForAccess:
          - devlake-mysql-db
