apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-app
spec:
  components:
    - name: rust-app-setup
      type: job
      properties:
        image: setup/rust-service
      traits:
        - type: scalar
          properties:
            replicas: 1  # ensure it's only run once
            restartPolicy: Never
        - type: s3
          properties:
            allow:
              - read
              - write
        - type: dynamo
          properties:
            allow:
              - read
              - write
              - create
        - type: cdn
          properties:
            allow:
              - read
              - write
    - name: rust-app-deployment
      type: webservice
      properties:
        image: app/rust-service
        port: 8080
      traits:
        - type: dynamo
          properties:
            allow:
              - read
              - write
  policies:
    - name: deploy-ha
      properties:
        components:
          - type: webservice
            traits:
              - type: scalar
                properties:
                  replicas: 3
