apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-svc
spec:
  components:
    - name: rust-svc
      type: appmod-service
      properties:
        image:  771830474512.dkr.ecr.us-west-2.amazonaws.com/app/rust-svc
        image_name: rust-app
        port: 8080
      traits:
        - type: path-based-ingress
          properties:
            domain: "*.amazonaws.com"
            rewritePath: "/rust-app"
            http:
              /rust-app: 8080
        - type: aws-service-account
          properties:
            componentNamesForAccess:
              - rust-dynamo
            clusterRegion: us-west-2
            clusterName: modern-engineering
    - name: rust-s3
      type: s3-bucket
      properties:
        region: us-west-2
        name: rust-bucket-12345
      traits:
        - type: component-iam-policy
          properties:
            service: s3
    - name: rust-ddb
      type: dynamodb
      properties:
        region: us-west-2

      traits:
        - type: component-iam-policy
          properties:
            service: dynamodb

