apiVersion: v1
kind: Service
metadata:
  name: rust-app-svc
  namespace: argo-rollouts  # TODO: Change this before going to workshop
spec:
  selector:
    app: rust-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rust-app-ingress
  namespace: argo-rollouts
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rust-app-svc
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rust-app-internal-svc
  namespace: argo-rollouts  # TODO: Change this before going to workshop
spec:
  selector:
    app: rust-app
  ports:
    - port: 80
      targetPort: 8080