apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-svc  # rust-app-svc.argo-rollouts.svc.cluster.local
  namespace: rust-msvc  # TODO: Change this before going to workshop
spec:
  selector:
    app: next-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: next-app-ingress
  namespace: rust-msvc
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-app-svc
                port:
                  number: 80
