apiVersion: batch/v1
kind: Job
metadata:
  name: create-env-aurora-postgres-${{values.name}}
  namespace: ${{values.namespace}}
spec:
  template:
    spec:
      containers:
      - name: trigger
        image: amazon/aws-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          aws --region ${{values.aws_region}} codebuild start-build --project-name db-modernengg-codebuild
        envFrom:
        - secretRef:
            name: aws-credentials
      restartPolicy: Never

