apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-addon-registry
  namespace: {{ .Release.Namespace }}
data:
  registries: '{
  "kubevela":{
    "name": "kubevela",
    "helm": {
      "url": "https://kubevela.github.io/catalog/official"
    }
  }
}'
