apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/alias: ""
    definition.oam.dev/description: AWS S3 Bucket
  name: s3-bucket
spec:
  schematic:
    cue:
      template: |
        output: {
                apiVersion: "awsblueprints.io/v1alpha1"
                kind:       "ObjectStorage"
                metadata: name: context.name
                spec: {
                        compositionSelector: matchLabels: {
                                "awsblueprints.io/provider":         "aws"
                                "awsblueprints.io/environment":      parameter.environment
                                "s3.awsblueprints.io/configuration": parameter.configuration
                        }
                        writeConnectionSecretToRef: name: "\(context.name)-info"
                        resourceConfig: {
                                providerConfigName: parameter.providerConfigName
                                region:             parameter.region
                                tags: [
                                        "\(Name):\(context.name)",
                                ]
                        }
                }
        }
        parameter: {
                environment:        string
                configuration:      string
                providerConfigName: string
                region:             string
        }
  workload:
    definition:
      apiVersion: aws-service/v1
      kind: Bucket


  ░▒▓    ~/WorkDocsDownloads/AWS_Internal/Containers/appmod-blueprints    feature/velaS3Templating +2 !3 ?1 ▓▒░                                                          ░▒▓ 15:21:13  ▓▒░─╮
  ❯ vela def vet ./platform/components/s3-bucket.cue                                                                                                                                             ─╯
  Validation ./platform/components/s3-bucket.cue succeed.
  
  ░▒▓    ~/WorkDocsDownloads/AWS_Internal/Containers/appmod-blueprints    feature/velaS3Templating +2 !3 ?1 ▓▒░                                                          ░▒▓ 15:28:33  ▓▒░─╮
  ❯ vela def render ./platform/components/s3-bucket.cue >> ./deployment/addons/vela-core/templates/s3-bucket.yaml                                                                                ─╯
--- s3-bucket.cue ---
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/alias: ""
    definition.oam.dev/description: AWS S3 Bucket
  name: s3-bucket
spec:
  schematic:
    cue:
      template: |
        output: {
                apiVersion: "awsblueprints.io/v1alpha1"
                kind:       "ObjectStorage"
                metadata: name: context.name
                spec: {
                        compositionSelector: matchLabels: {
                                "awsblueprints.io/provider":         "aws"
                                "awsblueprints.io/environment":      parameter.environment
                                "s3.awsblueprints.io/configuration": parameter.configuration
                        }
                        writeConnectionSecretToRef: name: "\(context.name)-info"
                        resourceConfig: {
                                providerConfigName: parameter.providerConfigName
                                region:             parameter.region
                                tags: [
                                        "name: \(context.name)",
                                ]
                        }
                }
        }
        parameter: {
                environment:        string
                configuration:      string
                providerConfigName: string
                region:             string
        }
  workload:
    definition:
      apiVersion: aws-service/v1
      kind: Bucket
