{{ if .Values.velaux.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: enable-velaux
  labels:
  {{- include "kubevela.labels" . | nindent 4 }}
    app: vela-cli
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: enable-velaux
      labels:
      {{- include "kubevela.labels" . | nindent 8 }}
        app: vela-cli
    spec:
      containers:
        - name: install
          image: {{ .Values.image.registry }}{{ .Values.image.cliRepository }}:{{ .Values.image.tag }}
          args:
            - addon
            - enable
            - velaux
            - --version={{ .Values.image.velauxTag }}
            - serviceAccountName={{ include "kubevela.serviceAccountName" . }}
            - serviceType={{ .Values.velaux.serviceType }}
            - repo=hub.kubevela.net
      restartPolicy: OnFailure
      serviceAccountName: {{ include "kubevela.serviceAccountName" . }}
{{ end }}
