apiVersion: batch/v1
kind: Job
metadata:
  name: javafunctest
spec:
  template:
    spec:
      containers:
      - name: javafunctest
        image: public.ecr.aws/i8e1q7x5/appmod-javafunctest:latest 
        args: ["k8s-kubesyst-blueprin-8bec7badbc-8ff52b36b01c1ee9.elb.us-west-2.amazonaws.com", "orange"]
      restartPolicy: Never

