apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/alias: ""
    definition.oam.dev/description: Amazon RDS MySQL Cluster
  name: rds-cluster-mysql
spec:
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "awsblueprints.io/v1alpha1"
        	kind:       "RelationalDatabase"
        	metadata: {
        		name:      context.name
        		namespace: context.namespace
        	}
        	spec: {
        		resourceConfig: {
        			name:           context.name
        			deletionPolicy: "Delete"
        			tags: {
        				Name:                 context.name
        				"crossplane-managed": "true"
        			}
        		}
        		databaseName: "\(context.name)db"
        		writeConnectionSecretToRef: {
        			name:      "\(context.name)-connection"
        			namespace: context.namespace
        		}
        	}
        }
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment

