apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.appname}}-cicd-sa
  namespace: ${{ values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{values.appname}}-cicd-sa-binding
  namespace: ${{ values.namespace }}
subjects:
- kind: ServiceAccount
  name: ${{values.appnam}}-cicd-sa
roleRef:
  kind: ClusterRole
  name: argo-workflow-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-runner
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/status
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
