apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vela-system 
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: deployment/addons/vela-core
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
