apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-n
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-n
    server: dev-server
  source:
    repoURL: http://cnoe-00d19caabc4d82fe.elb.us-west-2.amazonaws.com/gitea/giteaAdmin/dotnet.git
    targetRevision: main
    path: deployment/dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true