apiVersion: v1
kind: ConfigMap
metadata: 
  name: argo-rollouts-notification-configmap
  namespace: argo-rollouts
data:
  trigger.on-rollout-aborted: |
    - send: [modengg-rollout-aborted]
  trigger.on-rollout-completed: |
    - send: [modengg-rollout-completed]
  service.webhook.deployments: |
    url: https://${DNS_ENGINEERING}/argo-events/deployments
  template.modengg-rollout-aborted: |
    - stuff
  template.modengg-rollout-completed: |
    - stuff


