---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-rollout
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.deployments: ""
    notifications.argoproj.io/subscribe.on-rollout-aborted.deployments: ""
