apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-example-app
spec:
  components:
    - name: my-app-table
      type: dynamodb-table
      properties:
        tableName: my-app-table
        partitionKeyName: pk
        sortKeyName: sk
        region: us-west-2
      traits:
        - type: component-iam-policy
          properties:
            service: dynamodb

    - name: my-app-sa
      type: dp-service-account
      properties:
        name: my-app-service-account

    - name: my-app
      type: appmod-service
      properties:
        image: <account>.dkr.ecr.us-west-2.amazonaws.com/modernengg/my-app:latest
        image_name: my-app
        port: 8000
        targetPort: 8000
        replicas: 1
      traits:
        - type: path-based-ingress
          properties:
            domain: "*.elb.us-west-2.amazonaws.com"
            rewritePath: true
            http:
              "/my-app": 8000