apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: msvc-1
spec:
  components:
    - name: msvc-1-example
      type: appmod-service
      properties:
        image:  929819487611.dkr.ecr.us-west-2.amazonaws.com/modernengg/msvc-1:latest
        image_name: msvc-1
        port: 80
        targetPort: 80
        replicas: 1
      traits:
        - type: path-based-ingress
          properties:
            domain: "*.elb.us-west-2.amazonaws.com"
            rewritePath: true
            http:
              /northwind-app: 80

        - type: storage
          properties:
            secret:
              - name: msvc-1
                mountPath: /opt/secret-volume
  policies: # adopting secret that was generated outside of the app as readonly
    - type: read-only
      name: read-only
      properties:
        rules:
          - selector:
              resourceTypes: ["Secret"]
