apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-appmod-deployment
spec:
  selector:
    matchLabels:
      app: appmod-node
  replicas: 1
  template:
    metadata:
      labels:
        app: appmod-node
    spec:
      containers:
      - name: appmod-node
        image: public.ecr.aws/i8e1q7x5/appmod-node:latest 
        ports:
        - containerPort: 8080
