apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency-dev
scopes:
  - nodeapp
  - pythonapp
spec:
  policies:
    timeouts:
      general: 5s
      important: 60s
      largeResponse: 10s

    retries:
      pubsubRetry:
        policy: constant
        duration: 5s
        maxRetries: 10

      retryForever:
        policy: exponential
        maxInterval: 15s
        maxRetries: -1

      important:
        policy: constant
        duration: 5s
        maxRetries: 30

      someOperation:
        policy: exponential
        maxInterval: 15s

      largeResponse:
        policy: constant
        duration: 5s
        maxRetries: 3

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 30s
        trip: consecutiveFailures >= 5

      pubsubCB:
        maxRequests: 1
        interval: 8s
        timeout: 45s
        trip: consecutiveFailures > 8

  targets:
    apps:
      nodeapp:
        timeout: general
        retry: important
        circuitBreaker: simpleCB

      pythonapp:
        timeout: general
        retry: important
        circuitBreaker: simpleCB

    components:
      statestore:
        outbound:
          timeout: important
          retry: retryForever
          circuitBreaker: simpleCB

      pubsub:
        outbound:
          retry: pubsubRetry
          circuitBreaker: pubsubCB