apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: modern-engg 
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.4.8
      chart: argo-events
      helm:
        releaseName: argo-events
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      path: packages/argo-events/dev/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-events
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
