apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: modern-engg
  source:
    repoURL: ${GITHUB_URL}
    targetRevision: 1.13.5
    helm:
      releaseName: dapr
    chart: dapr
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dapr-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true