apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-compositions-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aws-samples/appmod-blueprints
    targetRevision: HEAD
    path: "platform/crossplane/compositions"
  destination:
    name: 'prod-cluster'
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions: []
