apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aws-samples/appmod-blueprints
    targetRevision: main
    path: packages/crossplane-provider/dev/
  destination:
    name: 'prod-cluster'
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions: []
