apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-dev
  namespace: argocd
spec:
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.7.0
      helm:
        releaseName: ingress-nginx-dev
        valueFiles:
          - $values/packages/ingress-nginx/dev/values-dev.yaml
    - repoURL: https://github.com/elamaran11/cnoe-appmod-implementation
      targetRevision: feature/upgradeToPathBasedRouting
      ref: values
  destination:
    name: 'dev-cluster'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
