apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
    - name: java-webservice 
      type: appmod-service
      properties:
        image: public.ecr.aws/i8e1q7x5/appmod-demo:latest 
        image_name: java-app
        port: 8080
        # functionalGate:
        #   pause: "10s" 
        #   image: "public.ecr.aws/i8e1q7x5/appmod-javafunctest:latest"
        #   extraArgs: "orange"
        # performanceGate:
        #   pause: "10s"
        #   image: "public.ecr.aws/i8e1q7x5/javaperftest:latest"
      traits: 
        - type: path-based-ingress
          properties:
            domain: "*.amazonaws.com"
            rewritePath: "/java-app" 
            http:
              /java-app: 8080
